In [12]:
import pandas as pd
import sys

In [13]:
data = pd.read_table(sys.argv[1],
                     names = ["seq", "source", "feature", "start", "end", "strand", 
                              "score", "phase", "attributes", "protein"],
                     header = None)
data.head()

,seq,source,feature,start,end,strand,score,phase,attributes,protein
0,1,geneidblastx,CDS,19080,19419,246.51,-,0,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...,UniRef90_G1P8G2
1,1,geneidblastx,CDS,19080,19419,246.51,-,0,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...,UniRef90_Q14517
2,1,geneidblastx,CDS,19080,19419,246.51,-,0,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...,UniRef90_P55289-2
3,1,geneidblastx,CDS,19080,19419,246.51,-,0,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...,UniRef90_Q5RJH3
4,1,geneidblastx,CDS,19080,19419,246.51,-,0,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...,UniRef90_Q2PZL6

In [16]:
grouped_data = data.groupby( ["seq", "source", "feature", "start", "end",
                              "strand", "score", "phase",
                              "attributes"]).agg({"protein" : ','.join }).reset_index()

In [17]:
grouped_data.head()

,seq,source,feature,start,end,strand,score,phase,attributes,protein
0,1,geneidblastx,CDS,19080,19419,246.51,-,0,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...,"UniRef90_G1P8G2,UniRef90_Q14517,UniRef90_P5528..."
1,1,geneidblastx,CDS,19474,20391,15.34,-,0,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...,"UniRef90_G1P8G2,UniRef90_Q14517,UniRef90_P5528..."
2,1,geneidblastx,CDS,21634,22356,432.53,-,0,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...,"UniRef90_Q9H158,UniRef90_A0A0D9RYH1,UniRef90_Q..."
3,1,geneidblastx,CDS,22382,23935,612.07,-,0,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...,"UniRef90_Q9H158,UniRef90_A0A0D9RYH1,UniRef90_Q..."
4,1,geneidblastx,CDS,24719,26217,717.57,-,2,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...,"UniRef90_A0A2I2UCL3,UniRef90_Q2PZL6,UniRef90_Q..."

In [21]:
updated_attributes = [ x if y == '.' else x + f";ProteinIDs:{y}" for x, y in zip(grouped_data["attributes"].values, grouped_data["protein"].values) ]

In [24]:
grouped_data["attributes"] = updated_attributes
grouped_data.drop("protein", axis = 1, inplace = True)

In [25]:
grouped_data.write_csv(sys.argv[2],
                       sep = "\t",
                       header = None,
                       index = None)

,seq,source,feature,start,end,strand,score,phase,attributes
0,1,geneidblastx,CDS,19080,19419,246.51,-,0,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...
1,1,geneidblastx,CDS,19474,20391,15.34,-,0,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...
2,1,geneidblastx,CDS,21634,22356,432.53,-,0,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...
3,1,geneidblastx,CDS,22382,23935,612.07,-,0,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...
4,1,geneidblastx,CDS,24719,26217,717.57,-,2,ID=cds_1_1;Parent=mRNA_1_1;Target=geneidblastx...